#page title
page_title                                : Arxivy                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1467838196                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Arxivy                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Browse the latest arXiv papers.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Floris Chabert                                
your_link                                 : https://florischabert.github.io/Arxivy/                     
your_city                                 : Washington                                
email_address                             : chabertf@gmail.com
facebook_username                         :                                           
instagram_username                        : florischabert
twitter_username                          : florischabert
github_username                           : florischabert
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Browse
    description                           : Browse the latest research papers on your favorite subjects.
    fontawesome_icon_name                 : list-alt

  - title                                 : Library
    description                           : Bookmark the best papers in your personal library, synced across your devices for offline reading.
    fontawesome_icon_name                 : book-open

  - title                                 : Search
    description                           : Search arXiv for a specific paper title, author and/or abstract highlight.
    fontawesome_icon_name                 : search



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1
topbar_title_color                        : "#000000"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#bbbbbb"

link_color                                : "#b31b1b"

app_title_color                           : "#000000"
app_price_color                           : "#666666"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#b31b1b"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#b31b1b"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - PRIVACY.md
  - CNAME
